services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    env_file:
      - .env
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - 6500:5432
    volumes:
      - $PWD/volumes/db:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8089:8080
