services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - 6500:5432
    volumes:
      - gd-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8089:8080

volumes:
  gd-data:
